spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
